# Generated by Django 4.0.10 on 2024-04-26 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=100, unique=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_routes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
