# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - next-zcbus-docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://nextzcbus.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d6d06beace0e4b95862f7f4edab3955a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1009455af7a8415f9619b4c23cee9265 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: nextzcbus.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d6d06beace0e4b95862f7f4edab3955a }}/next-zcbus:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'next-zcbus-docker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_30d63815171443178475099442d9c67c }}
        images: 'nextzcbus.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d6d06beace0e4b95862f7f4edab3955a }}/next-zcbus:${{ github.sha }}'